///////////////////////////////////////////////////////////////////////////////
// beispieleClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "beispieleClassFactory.h"
#include "beispieleServices.h"
#include "beispieleVersion.h"
#include "ModuleBeispiel1.h"

BEGIN_CLASS_MAP(CbeispieleClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_beispieleCModuleBeispiel1, SRVNAME_BEISPIELE "!CModuleBeispiel1", CModuleBeispiel1)
///</AutoGeneratedContent>
END_CLASS_MAP()

CbeispieleClassFactory::CbeispieleClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_BEISPIELE));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(beispiele));
#endif //defined(TCDBG_UNIT_VERSION)
}

