///////////////////////////////////////////////////////////////////////////////
// beispieleInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "beispieleServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
