///////////////////////////////////////////////////////////////////////////////
// beispieleServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_beispiele = 0x3F000000;
#define SRVNAME_BEISPIELE "beispiele"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_beispieleCModuleBeispiel1 = {0x89b0aa11,0x788b,0x4d30,{0x8d,0x69,0x44,0xb0,0x15,0x40,0x0b,0x7e}};
const CTCID CID_beispieleCModuleBeispiel2Out = {0x8615fcc5,0x975f,0x4f3b,{0x80,0xbe,0xbb,0xcc,0x6e,0x71,0xec,0xb0}};
const CTCID CID_beispieleCModuleBeispiel2In = {0x315384d9,0xca5f,0x4e80,{0xba,0x24,0x62,0x72,0xbf,0x7c,0x43,0x10}};
const CTCID CID_beispieleCModuleBeispiel3Consumer = {0xbaab62b9,0xa81c,0x47c4,{0x83,0x83,0x71,0xc0,0xd5,0xc4,0x87,0xa0}};
const CTCID CID_beispieleCModuleBeispiel3Service = {0xa8bc3f86,0x0f56,0x49ae,{0xa1,0xf6,0x01,0x73,0xea,0xd4,0xa5,0xfe}};
const CTCID CID_beispieleCModuleBeispiel4PlcIoAdsCommunication = {0x65d2f4ee,0x375e,0x4de3,{0xa3,0x7c,0x08,0xfa,0x81,0x97,0x57,0xc3}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_ModuleBeispiel1CppMember = 0x00000001;
const PTCID PID_ModuleBeispiel2InParameter = 0x00000001;
const PTCID PID_ModuleBeispiel3ConsumerIPFancyService = 0x00000001;
const PTCID PID_ModuleBeispiel3ServiceFancyParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_602E8C46_BBA3_447B_A46B_00EB30A09F7E_INCLUDED_)
#define _TC_TYPE_602E8C46_BBA3_447B_A46B_00EB30A09F7E_INCLUDED_
typedef struct _FancyData
{
	ULONG Id;
	ULONG Value;
} FancyData, *PFancyData;
#endif // !defined(_TC_TYPE_602E8C46_BBA3_447B_A46B_00EB30A09F7E_INCLUDED_)

#if !defined(_TC_TYPE_1850F391_9711_44A8_9D7A_DAD0AAFDAC81_INCLUDED_)
#define _TC_TYPE_1850F391_9711_44A8_9D7A_DAD0AAFDAC81_INCLUDED_
enum MyAdsStatus : SHORT {
	ADS_STATUS_INIT = 0,
	ADS_STATUS_WAIT = 1,
	ADS_STATUS_ERRORADSCOM = 2,
	ADS_STATUS_ADD_NOTIFICATION = 3
};
#endif // !defined(_TC_TYPE_1850F391_9711_44A8_9D7A_DAD0AAFDAC81_INCLUDED_)

typedef struct _ModuleBeispiel2OutOutputs
{
	FancyData Fancy;
} ModuleBeispiel2OutOutputs, *PModuleBeispiel2OutOutputs;

typedef struct _ModuleBeispiel2InParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} ModuleBeispiel2InParameter, *PModuleBeispiel2InParameter;

typedef struct _ModuleBeispiel2InInputs
{
	FancyData Fancy;
} ModuleBeispiel2InInputs, *PModuleBeispiel2InInputs;

typedef struct _ModuleBeispiel2InMembers
{
	FancyData Fancy;
} ModuleBeispiel2InMembers, *PModuleBeispiel2InMembers;

typedef struct _ModuleBeispiel3ConsumerData
{
	FancyData FancyData;
} ModuleBeispiel3ConsumerData, *PModuleBeispiel3ConsumerData;

#pragma pack(push,1)
typedef struct _ModuleBeispiel4PlcIoAdsCommunicationInputs
{
	unsigned char PLCX;
} ModuleBeispiel4PlcIoAdsCommunicationInputs, *PModuleBeispiel4PlcIoAdsCommunicationInputs;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _ModuleBeispiel4PlcIoAdsCommunicationAdsData
{
	LONG hVariableNotification;
	LONG hVariableHandle;
	MyAdsStatus Status;
} ModuleBeispiel4PlcIoAdsCommunicationAdsData, *PModuleBeispiel4PlcIoAdsCommunicationAdsData;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _ModuleBeispiel4PlcIoAdsCommunicationOutputs
{
	BYTE AdsX;
} ModuleBeispiel4PlcIoAdsCommunicationOutputs, *PModuleBeispiel4PlcIoAdsCommunicationOutputs;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_ModuleBeispiel2OutOutputs 1
#define ADI_ModuleBeispiel2InInputs 0
#define ADI_ModuleBeispiel2InMembers 2
#define ADI_ModuleBeispiel3ConsumerData 1
#define ADI_ModuleBeispiel4PlcIoAdsCommunicationInputs 1
#define ADI_ModuleBeispiel4PlcIoAdsCommunicationAdsData 2
#define ADI_ModuleBeispiel4PlcIoAdsCommunicationOutputs 3
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
#if !defined(_TC_IID_4400D997_C606_47B2_8486_FA74A26F4E2F_INCLUDED_)
#define _TC_IID_4400D997_C606_47B2_8486_FA74A26F4E2F_INCLUDED_
TCOM_DECL_INTERFACE("4400d997-c606-47b2-8486-fa74a26f4e2f", IFancyService)
#endif // !defined(_TC_IID_4400D997_C606_47B2_8486_FA74A26F4E2F_INCLUDED_)

///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
