///////////////////////////////////////////////////////////////////////////////
// beispieleServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_beispiele = 0x3F000000;
#define SRVNAME_BEISPIELE "beispiele"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_beispieleCModuleBeispiel1 = {0x89b0aa11,0x788b,0x4d30,{0x8d,0x69,0x44,0xb0,0x15,0x40,0x0b,0x7e}};
const CTCID CID_beispieleCModuleBeispiel2Out = {0x8615fcc5,0x975f,0x4f3b,{0x80,0xbe,0xbb,0xcc,0x6e,0x71,0xec,0xb0}};
const CTCID CID_beispieleCModuleBeispiel2In = {0x315384d9,0xca5f,0x4e80,{0xba,0x24,0x62,0x72,0xbf,0x7c,0x43,0x10}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_ModuleBeispiel1CppMember = 0x00000001;
const PTCID PID_ModuleBeispiel2InParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_602E8C46_BBA3_447B_A46B_00EB30A09F7E_INCLUDED_)
#define _TC_TYPE_602E8C46_BBA3_447B_A46B_00EB30A09F7E_INCLUDED_
typedef struct _FancyData
{
	ULONG Id;
	ULONG Value;
} FancyData, *PFancyData;
#endif // !defined(_TC_TYPE_602E8C46_BBA3_447B_A46B_00EB30A09F7E_INCLUDED_)

typedef struct _ModuleBeispiel2OutOutputs
{
	FancyData Fancy;
} ModuleBeispiel2OutOutputs, *PModuleBeispiel2OutOutputs;

typedef struct _ModuleBeispiel2InParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} ModuleBeispiel2InParameter, *PModuleBeispiel2InParameter;

typedef struct _ModuleBeispiel2InInputs
{
	FancyData Fancy;
} ModuleBeispiel2InInputs, *PModuleBeispiel2InInputs;

typedef struct _ModuleBeispiel2InMembers
{
	FancyData Fancy;
} ModuleBeispiel2InMembers, *PModuleBeispiel2InMembers;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_ModuleBeispiel2OutOutputs 1
#define ADI_ModuleBeispiel2InInputs 0
#define ADI_ModuleBeispiel2InMembers 2
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
