///////////////////////////////////////////////////////////////////////////////
// beispieleClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "beispieleClassFactory.h"
#include "beispieleServices.h"
#include "beispieleVersion.h"
#include "ModuleBeispiel1.h"
#include "ModuleBeispiel2Out.h"
#include "ModuleBeispiel2In.h"
#include "ModuleBeispiel3Consumer.h"
#include "ModuleBeispiel3Service.h"

BEGIN_CLASS_MAP(CbeispieleClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_beispieleCModuleBeispiel1, SRVNAME_BEISPIELE "!CModuleBeispiel1", CModuleBeispiel1)
	CLASS_ENTRY(CID_beispieleCModuleBeispiel2Out, SRVNAME_BEISPIELE "!CModuleBeispiel2Out", CModuleBeispiel2Out)
	CLASS_ENTRY(CID_beispieleCModuleBeispiel2In, SRVNAME_BEISPIELE "!CModuleBeispiel2In", CModuleBeispiel2In)
	CLASS_ENTRY(CID_beispieleCModuleBeispiel3Consumer, SRVNAME_BEISPIELE "!CModuleBeispiel3Consumer", CModuleBeispiel3Consumer)
	CLASS_ENTRY(CID_beispieleCModuleBeispiel3Service, SRVNAME_BEISPIELE "!CModuleBeispiel3Service", CModuleBeispiel3Service)
///</AutoGeneratedContent>
END_CLASS_MAP()

CbeispieleClassFactory::CbeispieleClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_BEISPIELE));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(beispiele));
#endif //defined(TCDBG_UNIT_VERSION)
}

