///////////////////////////////////////////////////////////////////////////////
// beispieleServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_beispiele = 0x3F000000;
#define SRVNAME_BEISPIELE "beispiele"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_beispieleCModuleBeispiel1 = {0x89b0aa11,0x788b,0x4d30,{0x8d,0x69,0x44,0xb0,0x15,0x40,0x0b,0x7e}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
