///////////////////////////////////////////////////////////////////////////////
// ModuleBeispiel1.cpp
#include "TcPch.h"
#pragma hdrstop

#include "ModuleBeispiel1.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif
DEFINE_THIS_FILE()

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CModuleBeispiel1
BEGIN_INTERFACE_MAP(CModuleBeispiel1)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
///</AutoGeneratedContent>
END_INTERFACE_MAP()


IMPLEMENT_ITCOMOBJECT(CModuleBeispiel1)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CModuleBeispiel1)
IMPLEMENT_ITCADI(CModuleBeispiel1)
IMPLEMENT_ITCWATCHSOURCE(CModuleBeispiel1)

///////////////////////////////////////////////////////////////////////////////
// Set parameters of CModuleBeispiel1 
BEGIN_SETOBJPARA_MAP(CModuleBeispiel1)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_ModuleBeispiel1CppMember, m_CppMember)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CModuleBeispiel1 
BEGIN_GETOBJPARA_MAP(CModuleBeispiel1)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_ModuleBeispiel1CppMember, m_CppMember)
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of CModuleBeispiel1
BEGIN_OBJPARAWATCH_MAP(CModuleBeispiel1)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
	OBJPARAWATCH_VALUE(PID_ModuleBeispiel1CppMember, m_CppMember)
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CModuleBeispiel1
BEGIN_OBJDATAAREA_MAP(CModuleBeispiel1)
///<AutoGeneratedContent id="ObjectDataAreaMap">
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
// Constructor
CModuleBeispiel1::CModuleBeispiel1()
{
///<AutoGeneratedContent id="MemberInitialization">
	m_CppMember = 0;
///</AutoGeneratedContent>
}

///////////////////////////////////////////////////////////////////////////////
// Destructor
CModuleBeispiel1::~CModuleBeispiel1() 
{
}

///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CModuleBeispiel1)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CModuleBeispiel1::SetObjStatePS(PTComInitDataHdr pInitData)
{
	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CModuleBeispiel1::SetObjStateSO()
{
	HRESULT hr = S_OK;
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CModuleBeispiel1::SetObjStateOS()
{
	HRESULT hr = S_OK;
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT CModuleBeispiel1::SetObjStateSP()
{
	HRESULT hr = S_OK;
	return hr;
}
