///////////////////////////////////////////////////////////////////////////////
// ModuleBeispiel3Service.h
#pragma once

#include "beispieleInterfaces.h"

class CModuleBeispiel3Service 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public IFancyService
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST(CID_beispieleCModuleBeispiel3Service)
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CModuleBeispiel3Service();
	virtual	~CModuleBeispiel3Service();


///<AutoGeneratedContent id="InterfaceMembers">
	// IFancyService
	virtual HRESULT TCOMAPI GetFancyData(FancyData* pData);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	FancyData m_FancyParameter;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
///</AutoGeneratedContent>
};
