///////////////////////////////////////////////////////////////////////////////
// ModuleBeispiel1.h
#pragma once

#include "beispieleInterfaces.h"

class CModuleBeispiel1 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST(CID_beispieleCModuleBeispiel1)
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CModuleBeispiel1();
	virtual	~CModuleBeispiel1();

///<AutoGeneratedContent id="InterfaceMembers">
///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

///<AutoGeneratedContent id="Members">
	ULONG m_CppMember;
///</AutoGeneratedContent>
};
