///////////////////////////////////////////////////////////////////////////////
// ModuleBeispiel4PlcIoAdsCommunication.h
#pragma once

#include "beispieleInterfaces.h"
#include "AdsR0.h"

const ULONG	INVOKEID_VARIABLEHANDLE = 0x00000001;
const ULONG INVOKEID_NOTIFICATIONHANDLE = 0x00000002;
const ULONG INVOKEID_DEL_VARHANDLE = 0x00000003;
const ULONG INVOKEID_DEL_NOTIHANDLE = 0x00000004;

class CModuleBeispiel4PlcIoAdsCommunication 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
///</AutoGeneratedContent>
	, public CAdsR0FifoPort
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST(CID_beispieleCModuleBeispiel4PlcIoAdsCommunication)
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CModuleBeispiel4PlcIoAdsCommunication();
	virtual	~CModuleBeispiel4PlcIoAdsCommunication();


///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

	// ADS specific methods
	virtual	void AdsReadWriteCon(AmsAddr& rAddr, ULONG invokeId, ULONG nResult, ULONG cbLength, PVOID pData);
	virtual	void AdsWriteCon(AmsAddr& rAddr, ULONG invokeId, ULONG nResult);
	virtual	void AdsDeviceNotificationInd(AmsAddr& rAddr, ULONG invokeId, ULONG cbLength, AdsNotificationStream* pNotifications);
	virtual void AdsAddDeviceNotificationCon(AmsAddr& rAddr, ULONG invokeId, ULONG nResult, ULONG handle);
	virtual	void AdsDelDeviceNotificationCon(AmsAddr& rAddr, ULONG invokeId, ULONG nResult);

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	ModuleBeispiel4PlcIoAdsCommunicationInputs m_Inputs;
	ModuleBeispiel4PlcIoAdsCommunicationAdsData m_AdsData;
	ModuleBeispiel4PlcIoAdsCommunicationOutputs m_Outputs;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
///</AutoGeneratedContent>

	AmsAddr m_Addr;

};
